
---

- name: Install aptitude using apt 
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  apt: name="{{ item }}" state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Puts daemon.json @ /etc/docker
  template:
   src: ../templates/daemon.json.j2
   dest: /etc/docker/daemon.json
   owner:  "{{home_user}}"
   group:  "{{home_user}}"
   mode: '0777'

- name: Restart docker service daemon
  service:
   name: docker
   state: restarted

- name: Deploying cloudlens
  docker_container:
    name: "MY_CL_{{ inventory_hostname }}"
    image: "{{CloudlensManagerIP}}/sensor:latest"
    state: started
    network_mode: host
    capabilities:
     - NET_RAW
     - SYS_RESOURCE
     - SYS_MODULE
     - NET_ADMIN
    privileged: true
    restart_policy: on-failure
    command: --accept_eula yes --project_key {{ CLOUDLENS_PROJECT_KEY }} --server  {{CloudlensManagerIP}} --ssl_verify no  --custom_tags owner=gustavo type={{Type}}
